### ISSUE TITLE
I would like to have the basic development environment setup for the developers so that they can easily access the database, frontend server, and  backend server

### ISSUE THREAD

**Issue by 2goldtess** [CS3398-Jedda-Knights/CS3398-Jedda-S2018#19]

**Comment by 2goldtess** [comment]
- [ ] install angular cli
- [ ] install python locally
- [ ] install mysql workbench
